version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USERNAME: postgres
      POSTGRES_DATABASE: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data_ooad
    ports:
      - 5431:5432
  
volumes:
  dbdata: {}